### ISSUE TITLE
Downloads dont complete

### ISSUE THREAD

**Issue by destruck51** [thecoder75/liveme-tools#107]
When downloading broadcasts through LMT it will download all the chunks and then hang on "Clearing temporary files"

![image](https://user-images.githubusercontent.com/11647751/32982062-6ee28bd8-cc76-11e7-97dd-d72125d537ac.png)

The folder that im downloading to just has a temp folder thats empty.

![image](https://user-images.githubusercontent.com/11647751/32982077-9e777cc8-cc76-11e7-9d17-7f0d69f246e6.png)

Version 6.3.2 of LMT - was previously on 6.2.1 which ran fine.

Downloading files to a veracrypt volume initially, however it also happens when downloading to a normal drive. 

Running LMT from a veracrypt volume initially, however it also happens when running from a normal drive.

**Comment by thecoder75** [comment]
Your problem may be happening due to the fact that you're running the Educational version of Windows 10 which has some special limits and restrictions on it compare to regular Windows 10 alone.  This could be causing your problem.  You can downgrade to 6.2.1 for now but based on it being a Windows system, @polydragon will have to look into this more.

**Comment by thecoder75** [comment]
Keepthings - Today at 1:09 PM

i hope all is well. I see someone with windows is having the same issue... the new downloader is pretty fast... however, when all chunks are downloaded to a temp folder it seems they aren't getting a chance to be combined because the next download rewrites previous temp folder... so ive seen a bunch of streams get downloaded into their ts chunks, but the download queue menu stays stuck on "cleaning temporary files" and all the ts files are being deleted as soon as they have all downloaded without leaving a complete file anywhere....

**Comment by jaylittt** [comment]
Same issue with mac. using os x 10.131.1 and LMT 6.3.2 and 7.0.0 having the same download error. A temp folder is made with .ts file chunks and disappears right when all chunks are downloaded. If there is another file in the queue, it will fill the now empty temp folder with it's ts file and disappear when downloaded also. In other words, the ts files don't join to make a larger file, they just disappear and new downloads don't make a new temp folder, they go into the previous temp folder. Also, files do not show up as downloaded in LMT browser which i suppose is true, but the process of downloading all the ts chunks did occur. Last thing, after all chunks are downloaded, the download queue window shows that download as "cleaning temporary files" and stays marked that way. only way to get it out of the queue list is empty the whole queue...
thanks for all your work

**Comment by thecoder75** [comment]
In the temp folder do you see folders in there with the .TS chunks?

**Comment by polydragon** [comment]
I'm pretty sure this isn't some edge case based on OS version and it's instead an error or something I've overlooked, I'll look into it and see and if I can figure out what's going on.

**Comment by mmind99** [comment]
I see the same thing in Win 7 Ultimate.  Using 6.2.1 for now.  Excellent work on this project by the way.

**Comment by mmind99** [comment]
Just wanted to confirm everything works fine on my Win 10 system using 7.0.1.  Another note about the Win 7 system that doesn't work, it is a virtual machine.  But with that said, it has more resources available than most standard PCs.  It also runs 6.2.1 and all previous version fine.

**Comment by polydragon** [comment]
Released version 7.0.2 which *should* fix this issue. If the downloader still errors it will give a message as to why it failed. If the error was within ffmpeg it will save an error log in your downloads directory, so it will be easier to figure out the cause.

I'll leave it open for now, until I get confirmation from others that the bug is resolved.

**Comment by mmind99** [comment]
Perfect!  That fixed it on my Win 7 system.  Thanks so much, excellent job.

**Comment by thecoder75** [comment]
After a fresh reload of my computer, attempting to start the app I get this:
```
{ Error: ENOENT: no such file or directory, open '/Users/xxxxxxxx/Library/Application Support/LiveMeTools/download-queue-v2.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/xxxxxxxx/Library/Application Support/LiveMeTools/download-queue-v2.json' }
{ Error: ENOENT: no such file or directory, open '/Users/xxxxxxxx/Library/Application Support/LiveMeTools/downloadHistory.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/xxxxxxxx/Library/Application Support/LiveMeTools/downloadHistory.json' }
{ Error: Command failed: undefined --help
/bin/sh: undefined: command not found

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: 'undefined --help' }
[591:1122/095039.976447:ERROR:atom_bindings.cc(29)] Fatal error in V8: v8::ToLocalChecked Empty MaybeLocal.
```
And after this error the app closes without anything else showing.

**Comment by thecoder75** [comment]
The error seams to be related to the FFMPEG detection code.

**Comment by polydragon** [comment]
Not just for my download json files:

``Error: ENOENT: no such file or directory, open C:\Users\xxx\AppData\Roaming\LiveMeTools\livemetools_db.json'``

I'll add a check to see if these files exist or not on startup and handle it accordingly, for now. After I'll move the queue and download history over to the database.

**Comment by thecoder75** [comment]
I haven't been getting that and there should be code in there to prevent that error anyways.  I'll see if I can reproduce that one.

**Comment by polydragon** [comment]
It only seems to happen when the LiveMeTools directory doesn't exist. If the directory exists but the file doesn't it's OK, if neither exist then it errors.

Also I'm getting another error after fixing these file not found errors that I have no clue on where to begin to look to start to fix it.

``[1504:1123/145308.237:ERROR:atom_bindings.cc(29)] Fatal error in V8: v8::ToLocalChecked Empty MaybeLocal.``

**Comment by polydragon** [comment]
Found the cause of ``Fatal error in V8: v8::ToLocalChecked Empty MaybeLocal.``

You need to have at least one user saved in the favorites part of the database otherwise you get this error.

**Comment by polydragon** [comment]
*Should* be fixed in latest beta build of *7.0.4* whenever it gets built.

**Comment by thecoder75** [comment]
I've added some FFMPEG command options to the downloads module that may help fix some of the corrupt or flakey video files.  During my testing I downloaded 30 replays and had 5 that were bad on download but good in the player.  Hopefully this will also help fix any other minor FFMPEG errors that also appeared in the log file.

**Comment by Hopeful13** [comment]
The merging chunks issue seems to mainly have been fixed. Thanks for that. I've only ran into it once since i moved to version 7.02. I also checked a stream that i couldn't get passed an error that passed in the updated version which is a good sign.

In the newest versions though i've now run into another issue with the stream downloading.
Windows 10 64bit
Version 7.0.2 and 7.0.05
The first stream i tried after updating to 7.0.5 i got the error and it happened numerous times in 7.0.2 where it says:
A JavaScript error occured in the main process
Uncaught Exception
Error: EBUSY: resource busy or locked, unlink

The stream download does finish and even merge but it doesn't count toward a finished download with color change and then it gets stuck in "cleaning temporary files" which is similar to when it got stuck in merging chunks before to where i have to restart to program to get things going again because it remains stuck where no further downloads can progress they remain in a waiting position.

**Comment by thecoder75** [comment]
This was posted in the main chat:  !(image)[https://d2.dropfile.to/img/e1677bfcfc9045ad6b1f947234fc38fb.png]

It may help explain this latest issue too.

**Comment by mmind99** [comment]
Sorry if this is a stupid question, but where is the main chat?  Just wanted to make sure I wasn't missing a chat section somewhere.  Still new to github.

**Comment by thecoder75** [comment]
It's not on here, there's a Discord server with a chat room that people use for asking questions and posting information about errors in.

**Comment by thecoder75** [comment]
This is a bug that affected the chunk downloader created by @polydragon and was partially resolved in the 7.x.x branch.  Development of the 7.x.x branch has been suspended for now.
